import type { CountryConfig } from '../types';

// Fully built example: South Africa.
// Other countries are placeholders — add full localised data as needed.
export const COUNTRIES: CountryConfig[] = [
  {
    code: 'ZA',
    name: 'South Africa',
    currency: 'ZAR',
    currencySymbol: 'R',
    defaultGlucoseUnit: 'mmol/L',
    commonFoods: [
      'Eggs',
      'Chicken',
      'Tuna',
      'Brown rice',
      'Pap (maize meal)',
      'Vegetables',
      'Beans',
      'Lentils',
      'Oats',
      'Greek yoghurt',
      'Biltong',
      'Avocado',
      'Grilled meat',
      'Sweet potato',
      'Spinach (morogo)',
    ],
    groceryExamples: [
      { item: '6 eggs', price: 30 },
      { item: '1kg chicken', price: 95 },
      { item: 'Tuna tin (170g)', price: 28 },
      { item: 'Brown rice 1kg', price: 38 },
      { item: 'Maize meal 2.5kg', price: 55 },
      { item: 'Mixed veg 1kg', price: 45 },
      { item: 'Lentils 500g', price: 32 },
      { item: 'Rolled oats 1kg', price: 48 },
      { item: 'Greek yoghurt 1kg', price: 65 },
      { item: 'Avocado (each)', price: 12 },
    ],
    mealPriceLow: 25,
    mealPriceMid: 55,
    mealPriceHigh: 110,
    fullySupported: true,
  },
  {
    code: 'US',
    name: 'United States',
    currency: 'USD',
    currencySymbol: '$',
    defaultGlucoseUnit: 'mg/dL',
    commonFoods: ['Eggs', 'Chicken breast', 'Salmon', 'Brown rice', 'Black beans', 'Spinach', 'Greek yoghurt', 'Avocado', 'Quinoa'],
    groceryExamples: [
      { item: 'Dozen eggs', price: 4.5 },
      { item: 'Chicken breast 1lb', price: 5.5 },
      { item: 'Brown rice 2lb', price: 4 },
    ],
    mealPriceLow: 4,
    mealPriceMid: 9,
    mealPriceHigh: 16,
    fullySupported: false,
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    currency: 'GBP',
    currencySymbol: '£',
    defaultGlucoseUnit: 'mmol/L',
    commonFoods: ['Eggs', 'Chicken', 'Salmon', 'Wholegrain bread', 'Baked beans', 'Porridge oats', 'Greek yoghurt', 'Spinach'],
    groceryExamples: [
      { item: 'Dozen eggs', price: 2.8 },
      { item: 'Chicken breast 500g', price: 4.5 },
    ],
    mealPriceLow: 3,
    mealPriceMid: 7,
    mealPriceHigh: 14,
    fullySupported: false,
  },
  {
    code: 'AU',
    name: 'Australia',
    currency: 'AUD',
    currencySymbol: 'A$',
    defaultGlucoseUnit: 'mmol/L',
    commonFoods: ['Eggs', 'Chicken', 'Barramundi', 'Wholemeal bread', 'Lentils', 'Oats', 'Greek yoghurt', 'Avocado'],
    groceryExamples: [
      { item: 'Dozen eggs', price: 6.5 },
      { item: 'Chicken breast 1kg', price: 12 },
    ],
    mealPriceLow: 6,
    mealPriceMid: 12,
    mealPriceHigh: 22,
    fullySupported: false,
  },
  {
    code: 'IN',
    name: 'India',
    currency: 'INR',
    currencySymbol: '₹',
    defaultGlucoseUnit: 'mg/dL',
    commonFoods: ['Dal', 'Chickpeas', 'Brown rice', 'Roti (whole wheat)', 'Paneer', 'Spinach (palak)', 'Curd', 'Eggs', 'Chicken'],
    groceryExamples: [
      { item: '1 dozen eggs', price: 90 },
      { item: 'Toor dal 1kg', price: 160 },
    ],
    mealPriceLow: 60,
    mealPriceMid: 120,
    mealPriceHigh: 250,
    fullySupported: false,
  },
  {
    code: 'CA',
    name: 'Canada',
    currency: 'CAD',
    currencySymbol: 'C$',
    defaultGlucoseUnit: 'mmol/L',
    commonFoods: ['Eggs', 'Chicken', 'Salmon', 'Wild rice', 'Lentils', 'Oats', 'Greek yoghurt', 'Avocado'],
    groceryExamples: [
      { item: 'Dozen eggs', price: 4.2 },
      { item: 'Chicken breast 1kg', price: 14 },
    ],
    mealPriceLow: 5,
    mealPriceMid: 10,
    mealPriceHigh: 18,
    fullySupported: false,
  },
];

export const getCountry = (code: string): CountryConfig => {
  return COUNTRIES.find((c) => c.code === code) ?? COUNTRIES[0];
};
